spring:
  profiles:
    active: dev
    include: wf,config
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  aop:
    auto: true
    proxy-target-class: true
  resources:
    static-locations: [classpath:/static/]
  session:
    store-type: redis
  devtools:
    restart:
      enabled: true
  freemarker:
    check-template-location: false
  #配置文件传输
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 300MB
      file-size-threshold: 0
      enabled: true
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml,sqlservermapper/**/*Mapper.xml,oraclemapper/**/*Mapper.xml,classpath*:com/**/*Mapper.xml
  config-location: classpath:config/mybatis-config.xml
  global-config:
    db-config:
      id-type: auto
      field-strategy: NOT_NULL
      # 驼峰下划线转换
      db-column-underline: true
